FROM python:3.11-slim

WORKDIR /app

# Устанавливаем flask и gunicorn
RUN pip install flask gunicorn

# Копируем тестовое приложение
COPY test_app.py .

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "test_app:app"]